stripe:
  public_key: pk_test_51IuXqOBmTxR6KoZuWexjvQV9GiKworxBkZBwSTycWswZyo2e2OR8FXmKRfqZFfMHauUHGcHuGNgiRiGGm4XfyG7n00UIl5Bcwx
  private_key: sk_test_51IuXqOBmTxR6KoZuGFYUsktxAUQu0Wa79GOvU73Y0tEcKE9zWSb7IipyjVxTnlhMbyrR3GuhwNweTZyef7VnXFOs00yJ0E7cP0
  signing_secret: whsec_0ad3d178d65ea18efb3dd373af86ca62f985e9a93c44df818cb9a4041aee10b7